version: "3"

services:
  adminer:
    image: adminer:4.7
    container_name: adminer
    restart: always
    networks:
      - db
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.rule=Host(`adminer.rasp-server.tk`)
      - traefik.http.routers.adminer.entrypoints=web
      - traefik.http.services.adminer.loadbalancer.server.port=8080

networks:
  traefik:
    external: true
  db:
    external: true