version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    restart: always
    networks:
      - traefik
    #environment:
    #  -
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../../certs/cloudflareCA_RSA_root.crt:/etc/ssl/certs/cloudflareCA_RSA_root.crt:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.rasp-server.tk`)
      - traefik.http.routers.prometheus.entrypoints=websecure
      - traefik.http.routers.prometheus.service=prometheus-svc
      - traefik.http.services.prometheus-svc.loadbalancer.server.port=9090

networks:
  traefik:
    external: true