version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
#auth:
#  htpasswd:
#    realm: basic-realm
#    path: /auth/htpasswd
http:
  addr: :5000
  #tls:
  #  certificate: /certs/rasp-server.tk.pem
  #  key: /certs/rasp-server.tk.key
  debug:
    addr: :5001
    prometheus:
      enabled: true
      path: /metrics
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3